[package]
name = "emperust"
version = "0.1.0"
authors = ["Jesper Fridefors <jesper.fridefors@gmail.com>"]

[dependencies]
yaml-rust = "*"
num = "*"
itertools = "0.4"
rand = "0.3"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs"
