[package]
name = "emperust2"
version = "0.1.0"
authors = ["Jesper Fridefors <jesper.fridefors@gmail.com>"]

[dependencies]
yaml-rust = "*"
num = "*"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs"
