font_path: fonts/arial10x10.png
title: Min skit
main_window:
    width: 180
    height: 100
map_window:
    width: 100
    height: 60
zoomed_map_window:
    width: 60
    height: 60
map:
    width: 250
    height: 250
height_map:
    coefficient: 0.02
    lacunarity: 8.0
    hurst: 16.0
temperature:
    y_dependence: 0.2
    turbulence: 12.0
    turbulence_dependence: 0.3
world_gen:
    tree_line: 170
    ocean_line: 140
debug_window:
    width: 50
    height: 50