font_path: fonts/arial10x10.png
title: Min skit
main_window:
    width: 100
    height: 50
map_window:
    width: 30
    height: 30
map:
    width: 1000
    height: 1000
height_map:
    coefficient: 0.05
    lacunarity: 0.8
    hurst: 0.8