font_path: fonts/consolas10x10_gs_tc.png
title: Min skit
main_window:
    width: 180
    height: 100
map_window:
    width: 100
    height: 60
zoomed_map_window:
    width: 60
    height: 60
map:
    width: 1000
    height: 1000
height_map:
    coefficient: 0.015
    lacunarity: 8.0
    hurst: 16.0
temperature:
    y_dependence: 0.3
    turbulence: 6.0
    turbulence_dependence: 0.3
    coefficient: 0.025
rainfall:
    coefficient: 0.05
    height_dependence: 0.4
    turbulence: 6.0
    turbulence_dependence: 0.2
world_gen:
    tree_line: 167
    ocean_line: 140
debug_window:
    width: 50
    height: 50