font_path: fonts/arial10x10.png
title: Min skit
main_window:
    width: 150
    height: 100
map_window:
    width: 60
    height: 60
map:
    width: 500
    height: 500
height_map:
    coefficient: 0.05
    lacunarity: 8.0
    hurst: 16.0
world_gen:
    tree_line: 170
    ocean_line: 140