font_path: fonts/consolas10x10_gs_tc.png
title: Min skit
main_window:
    width: 100
    height: 75
map_window:
    width: 60
    height: 60
zoomed_map_window:
    width: 30
    height: 30
map:
    width: 500
    height: 500
height_map:
    coefficient: 0.006
    lacunarity: 8.0
    hurst: 16.0
temperature:
    y_dependence: 0.3
    turbulence: 6.0
    turbulence_dependence: 0.2
    coefficient: 0.03
rainfall:
    coefficient: 0.018
    height_dependence: 0.7
    turbulence: 3.0
    turbulence_dependence: 0.1
world_gen:
    tree_line: 167
    ocean_line: 130
    rivers: 5
history_gen:
    initial_cities: 0
debug_window:
    width: 50
    height: 50
